# Generated by Django 4.2.3 on 2023-07-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('format', models.CharField(max_length=50)),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('endtime', models.DateTimeField(db_column='endTime')),
                ('recupdatedat', models.DateTimeField(db_column='recUpdatedAt')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'matches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('recupdatedat', models.DateTimeField(db_column='recUpdatedAt')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'sports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('endtime', models.DateTimeField(db_column='endTime')),
                ('recupdatedat', models.DateTimeField(db_column='recUpdatedAt')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'tours',
                'managed': False,
            },
        ),
    ]
